const companies = [
  { name:"DataRobot", url:"https://www.datarobot.com/careers/open-positions/", note:"AI & ML platform, Boston", tags:["new","featured","enterprise","saas"] },
  { name:"10up", url:"https://10up.com/careers", note:"WordPress & digital agency", tags:["startup","devtools"] },
  { name:"AdHoc", url:"https://adhoc.team/join/", note:"Civic-tech digital services", tags:["startup"] },
  { name:"AirTreks", url:"https://www.airtreks.com/careers/", note:"Multi-stop travel agency", tags:["startup"] },
  { name:"Cards Against Humanity", url:"https://cardsagainsthumanity.com/jobs/", note:"Game company", tags:["startup"] },
  { name:"Clevertech", url:"https://clevertech.biz/careers/", note:"Remote dev consultancy", tags:["startup","devtools"] },
  { name:"Discourse", url:"https://www.discourse.org/careers", note:"Open-source forum platform", tags:["startup","devtools"] },
  { name:"Formstack", url:"https://www.formstack.com/jobs", note:"Forms & workflow automation", tags:["saas"] },
  { name:"Gem", url:"https://www.gem.com/careers", note:"Recruiting platform", tags:["saas","startup"] },
  { name:"GrooveHQ", url:"https://www.groovehq.com/about/careers", note:"Customer support helpdesk", tags:["saas","startup"] },
  { name:"15Five", url:"https://www.15five.com/careers", note:"Employee engagement & HR", tags:["saas"] },
  { name:"37signals", url:"https://37signals.com/jobs", note:"Basecamp & HEY maker", tags:["featured","saas","devtools"] },
  { name:"Aha!", url:"https://www.aha.io/company/careers", note:"Product roadmap software", tags:["saas"] },
  { name:"AirGarage", url:"https://www.airgarage.com/careers", note:"Parking automation platform", tags:["startup"] },
  { name:"Hello Bonsai", url:"https://www.hellobonsai.com/careers", note:"Freelancer business tools", tags:["saas","startup"] },
  { name:"Buffer", url:"https://buffer.com/journey", note:"Social media management", tags:["featured","saas"] },
  { name:"Cabify", url:"https://cabify.com/en/jobs", note:"Ride-hailing, Spain & LatAm", tags:["startup"] },
  { name:"Capchase", url:"https://www.capchase.com/careers", note:"Revenue-based financing fintech", tags:["startup"] },
  { name:"Capmo", url:"https://www.capmo.com/en/career", note:"Construction mgmt SaaS (DE)", tags:["saas","startup"] },
  { name:"ChefsClub", url:"https://www.chefsclub.com.br/carreiras", note:"Restaurant deals app (Brazil)", tags:["startup"] },
  { name:"Doist", url:"https://doist.com/careers", note:"Todoist & Twist maker", tags:["featured","saas"] },
  { name:"Etsy", url:"https://www.etsy.com/careers", note:"Global handmade marketplace", tags:["featured","enterprise"] },
  { name:"GitHub", url:"https://github.careers", note:"Microsoft-owned dev platform", tags:["featured","devtools","enterprise"] },
  { name:"GoDaddy", url:"https://careers.godaddy.com", note:"Domain & web hosting", tags:["enterprise"] },
  { name:"Greenhouse", url:"https://www.greenhouse.io/careers", note:"Applicant tracking system", tags:["saas"] },
  { name:"Gusto", url:"https://gusto.com/about/careers", note:"Payroll & HR platform", tags:["featured","saas"] },
  { name:"90seconds", url:"https://90seconds.com/careers", note:"On-demand video production", tags:["startup"] },
  { name:"Aerolab", url:"https://aerolab.co/careers", note:"Product design studio (Argentina)", tags:["startup"] },
  { name:"Alan", url:"https://alan.com/careers", note:"Health insurance (France)", tags:["startup","saas"] },
  { name:"BairesDev", url:"https://www.bairesdev.com/careers", note:"Nearshore software dev", tags:["enterprise"] },
  { name:"Boldare", url:"https://www.boldare.com/careers", note:"Digital product studio (Poland)", tags:["startup"] },
  { name:"Bugfender", url:"https://bugfender.com/careers", note:"Remote logging & bug tracking", tags:["devtools","startup"] },
  { name:"Casumo", url:"https://www.casumo.com/careers", note:"Online casino platform", tags:["startup"] },
  { name:"CareMessage", url:"https://caremessage.org/careers", note:"Nonprofit health texting", tags:["nonprofit","startup"] },
  { name:"Dropbox", url:"https://dropbox.com/jobs", note:"Cloud storage & collaboration", tags:["featured","enterprise","saas"] },
  { name:"Evernote", url:"https://evernote.com/careers", note:"Note-taking app (Bending Spoons)", tags:["saas"] },
  { name:"Figma", url:"https://www.figma.com/careers", note:"Collaborative design platform", tags:["featured","devtools","saas"] },
  { name:"Glovo", url:"https://glovoapp.com/en/jobs", note:"On-demand delivery (Europe)", tags:["startup","enterprise"] },
  { name:"Grab", url:"https://grab.careers", note:"Super-app, Southeast Asia", tags:["enterprise"] },
  { name:"Abiturma", url:"https://www.abiturma.de/jobs", note:"German education platform", tags:["startup"] },
  { name:"AbstractAPI", url:"https://www.abstractapi.com/careers", note:"API infrastructure tools", tags:["devtools","startup"] },
  { name:"Acquia", url:"https://www.acquia.com/careers", note:"Drupal cloud platform", tags:["saas","enterprise"] },
  { name:"Adaface", url:"https://www.adaface.com/careers", note:"Pre-employment screening", tags:["saas","startup"] },
  { name:"Adzuna", url:"https://www.adzuna.com/jobs", note:"Job search engine", tags:["startup"] },
  { name:"Ably", url:"https://ably.com/careers", note:"Realtime messaging infrastructure", tags:["devtools","startup"] },
  { name:"Airbyte", url:"https://airbyte.com/careers", note:"Open-source data integration", tags:["featured","devtools","startup"] },
  { name:"Akka", url:"https://akka.io/careers", note:"Reactive systems framework", tags:["devtools"] },
  { name:"Algorand", url:"https://www.algorand.com/careers", note:"Blockchain & smart contracts", tags:["startup"] },
  { name:"BlueCat Networks", url:"https://bluecatnetworks.com/company/careers", note:"DNS & network mgmt", tags:["enterprise"] },
  { name:"Bluespark", url:"https://www.bluespark.com/careers", note:"Drupal web agency", tags:["startup"] },
  { name:"Bounteous", url:"https://www.bounteous.com/careers", note:"Digital experience consulting", tags:["enterprise"] },
  { name:"Brainstorm Force", url:"https://brainstormforce.com/careers", note:"WordPress plugin & theme maker", tags:["startup"] },
  { name:"Brikl", url:"https://www.brikl.com/careers", note:"Custom merch e-commerce", tags:["startup","saas"] },
  { name:"BriteCore", url:"https://britecore.com/careers", note:"Insurance tech platform", tags:["saas"] },
  { name:"BuySellAds", url:"https://www.buysellads.com/careers", note:"Developer-focused ad network", tags:["startup"] },
  { name:"Calibre", url:"https://calibreapp.com/careers", note:"Web performance monitoring", tags:["devtools","startup"] },
  { name:"Canonical", url:"https://canonical.com/careers", note:"Ubuntu & open-source OS", tags:["featured","devtools","enterprise"] },
  { name:"Carto", url:"https://carto.com/careers", note:"Location intelligence platform", tags:["saas","startup"] },
  { name:"Chainlink Labs", url:"https://chainlinklabs.com/careers", note:"Blockchain oracle network", tags:["startup"] },
  { name:"Maxio", url:"https://www.maxio.com/careers", note:"Subscription billing (Chargify+)", tags:["saas"] },
  { name:"Chess.com", url:"https://www.chess.com/jobs", note:"Online chess platform", tags:["startup"] },
  { name:"Chromatic", url:"https://www.chromatic.com/careers", note:"UI testing for Storybook", tags:["devtools","startup"] },
  { name:"CivicActions", url:"https://civicactions.com/careers", note:"Civic tech / gov digital services", tags:["nonprofit","startup"] },
  { name:"Clootrack", url:"https://www.clootrack.com/careers", note:"Customer analytics AI", tags:["saas","startup"] },
  { name:"Close", url:"https://close.com/jobs", note:"CRM for startups & SMBs", tags:["featured","saas","startup"] },
  { name:"Duolingo", url:"https://careers.duolingo.com", note:"Language learning app", tags:["featured","enterprise"] },
  { name:"Foursquare", url:"https://foursquare.com/careers", note:"Location data company", tags:["enterprise","saas"] },
  { name:"ActiveCampaign", url:"https://www.activecampaign.com/careers", note:"Email & marketing automation", tags:["saas","enterprise"] },
  { name:"Adevait", url:"https://adevait.com/careers", note:"Dev talent network", tags:["startup"] },
  { name:"Calamari", url:"https://calamari.io/careers", note:"HR & leave management", tags:["saas","startup"] },
  { name:"CartStack", url:"https://www.cartstack.com/careers", note:"Cart abandonment recovery", tags:["saas","startup"] },
  { name:"GitLab", url:"https://about.gitlab.com/jobs", note:"DevOps platform (all-remote)", tags:["featured","devtools","enterprise"] },
  { name:"1Password", url:"https://1password.com/careers", note:"Password manager", tags:["featured","saas"] },
  { name:"Agflow", url:"https://agflow.com/careers", note:"Commodity & grain data", tags:["startup"] },
  { name:"Cancom", url:"https://www.cancom.com/careers", note:"IT services (Germany/Austria)", tags:["enterprise"] },
  { name:"Capgemini", url:"https://www.capgemini.com/careers", note:"Global IT consulting", tags:["featured","enterprise"] },
  { name:"Civo", url:"https://www.civo.com/careers", note:"Kubernetes cloud platform", tags:["devtools","startup"] },
  { name:"Docker", url:"https://www.docker.com/careers", note:"Container platform", tags:["featured","devtools","enterprise"] },
  { name:"HashiCorp", url:"https://www.hashicorp.com/careers", note:"Infrastructure automation (IBM)", tags:["featured","devtools","enterprise"] },
  { name:"Capital One", url:"https://www.capitalonecareers.com", note:"Major US bank", tags:["enterprise"] },
  { name:"Charity: Water", url:"https://www.charitywater.org/careers", note:"Clean water nonprofit", tags:["nonprofit"] },
  { name:"Fivetran", url:"https://fivetran.com/careers", note:"Data pipeline automation", tags:["saas","devtools"] },
  { name:"Akamai", url:"https://www.akamai.com/careers", note:"CDN & cybersecurity", tags:["enterprise"] },
  { name:"Fortinet", url:"https://www.fortinet.com/corporate/careers", note:"Network security platform", tags:["enterprise"] },
  { name:"E*TRADE", url:"https://us.etrade.com/careers", note:"Online brokerage (Morgan Stanley)", tags:["enterprise"] },
  { name:"Evo", url:"https://evo.com/careers", note:"Outdoor gear retailer", tags:["startup"] },
  { name:"Eventbrite", url:"https://www.eventbritecareers.com", note:"Event ticketing platform", tags:["enterprise","saas"] },
  { name:"Flexport", url:"https://www.flexport.com/careers", note:"Freight & logistics tech", tags:["enterprise","startup"] },
  { name:"Gainsight", url:"https://www.gainsight.com/careers", note:"Customer success platform", tags:["saas"] },
  { name:"Glassdoor", url:"https://www.glassdoor.com/about-us/jobs", note:"Jobs & company reviews", tags:["enterprise"] },
  { name:"Gojek", url:"https://www.gojek.io/careers", note:"Super-app, Indonesia/GoTo", tags:["enterprise"] },
  { name:"Google", url:"https://careers.google.com", note:"Global tech giant", tags:["featured","enterprise"] },
  { name:"Grafana Labs", url:"https://grafana.com/about/careers", note:"Observability & monitoring", tags:["featured","devtools","startup"] },
  { name:"Grubhub", url:"https://www.grubhub.com/careers", note:"Food delivery platform", tags:["enterprise"] },
  { name:"HackerRank", url:"https://www.hackerrank.com/careers", note:"Coding assessment platform", tags:["saas"] },
  { name:"Hootsuite", url:"https://hootsuite.com/careers", note:"Social media management", tags:["saas","enterprise"] },
  { name:"HubSpot", url:"https://www.hubspot.com/careers", note:"CRM & marketing platform", tags:["featured","saas","enterprise"] },
  { name:"ClickUp", url:"https://clickup.com/careers", note:"All-in-one project management", tags:["featured","saas"] },

  // ── Job Finder / India ──
  { name:"Freshers.info", url:"https://freshers.info/#gsc.tab=0", note:"Fresher jobs & resources India", tags:["new","jobboard","india"] },
  { name:"Internshala", url:"https://internshala.com/student/dashboard", note:"Internships & fresher jobs India", tags:["new","featured","jobboard","india"] },
  { name:"Freshersworld", url:"https://www.freshersworld.com/", note:"Fresher jobs, govt jobs India", tags:["new","jobboard","india"] },
  { name:"Best Jobs Online (India)", url:"https://in.best-jobs-online.com/", note:"1M+ jobs across India", tags:["new","jobboard","india"] },
  { name:"Best Jobs Online (Web Dev)", url:"https://jobs.best-jobs-online.com/jobs?q=Web+development&l=", note:"Web dev jobs, Bhopal/India", tags:["new","jobboard","india"] },
  { name:"Jobrapido India", url:"https://in.jobrapido.com/", note:"Aggregated job search India", tags:["new","jobboard","india"] },
  { name:"Shine.com", url:"https://www.shine.com/", note:"Job search & recruitment India", tags:["new","featured","jobboard","india"] },
  { name:"FresherJob.in", url:"https://fresherjob.in/", note:"Entry level & fresher jobs India", tags:["new","jobboard","india"] },
  { name:"Foundit (Monster)", url:"https://www.foundit.in/user", note:"Formerly Monster India", tags:["new","jobboard","india"] },
  { name:"Fishbowl", url:"https://www.fishbowlapp.com/feed", note:"Professional community & jobs", tags:["new","jobboard"] },
  { name:"Superset", url:"https://app.joinsuperset.com/students", note:"Campus & fresher hiring India", tags:["new","featured","jobboard","india"] },
  { name:"Talent Titan (Mahindra)", url:"https://talenttitan.com/candidates/hiring-drives/mahindra-campus-hiring/", note:"Mahindra campus hiring drive", tags:["new","jobboard","india","enterprise"] },
  { name:"TrueUp", url:"https://www.trueup.io/", note:"Tech job & layoff tracker", tags:["new","devtools","jobboard"] },
  { name:"Contra", url:"https://contra.com/features/find-freelance-jobs", note:"Global freelance job platform", tags:["new","remote","jobboard"] },
  { name:"Wellfound (AngelList)", url:"https://wellfound.com/", note:"Startup jobs & AngelList talent", tags:["new","featured","jobboard","startup"] },
  { name:"Virtual Vocations", url:"https://www.virtualvocations.com/", note:"Remote & work-from-home jobs", tags:["new","remote","jobboard"] },
  { name:"Working Nomads", url:"https://www.workingnomads.com/jobs", note:"Remote jobs for digital nomads", tags:["new","remote","jobboard"] },
  { name:"Working Nomads India Dev", url:"https://www.workingnomads.com/jobs?location=india&category=development", note:"Remote dev jobs from India", tags:["new","remote","jobboard","india"] },
  { name:"RemoteOK (Software)", url:"https://remoteok.com/remote-software-engineer-jobs", note:"Remote software engineer jobs", tags:["new","featured","remote","devtools","jobboard"] },
  { name:"Pangian", url:"https://pangian.com/remote/", note:"Remote jobs for digital nomads", tags:["new","remote","jobboard"] },
  { name:"Remote4Me", url:"https://remote4me.com/", note:"20+ job boards aggregated", tags:["new","remote","jobboard"] },
  { name:"Remotive (Software)", url:"https://remotive.com/remote-jobs/software-dev", note:"Remote software dev jobs", tags:["new","remote","devtools","jobboard"] },
  { name:"NoDesk", url:"https://nodesk.co/", note:"Remote jobs & resources", tags:["new","remote","jobboard"] },
  { name:"Toptal", url:"https://www.toptal.com/", note:"Top 3% freelance talent network", tags:["new","featured","remote","devtools"] },
  { name:"SimplyHired", url:"https://www.simplyhired.com/", note:"Job search engine, global", tags:["new","jobboard"] },
  { name:"AccioJob", url:"https://placement.acciojob.com/dashboard/", note:"Placement records & hiring India", tags:["new","jobboard","india"] },
  { name:"Simplify Jobs", url:"https://simplify.jobs/dashboard", note:"AI-powered job application tracker", tags:["new","jobboard","devtools"] },
  { name:"LazyApply", url:"https://app.lazyapply.com/dashboard", note:"Auto job application bot", tags:["new","jobboard","devtools"] },
  { name:"Glassdoor Community", url:"https://www.glassdoor.co.in/Community/index.htm", note:"Company reviews & salary info", tags:["new","jobboard","india"] },
  { name:"Workday Careers", url:"https://workday.wd5.myworkdayjobs.com/en-US/Workday/jobs", note:"Jobs at Workday", tags:["new","enterprise","saas"] },
  { name:"Stripe Jobs", url:"https://stripe.com/jobs/search", note:"Jobs at Stripe (global)", tags:["new","featured","enterprise","saas"] },
  { name:"Get Well Network", url:"https://job-boards.greenhouse.io/getwellnetwork", note:"Digital health company jobs", tags:["new","saas"] },
  { name:"EngineerHub", url:"https://engineerhub.in/career", note:"Jobs & internships India", tags:["new","jobboard","india","devtools"] },
  { name:"QuickHyre", url:"https://quickhyre.ai/jobs", note:"AI job matching platform", tags:["new","jobboard","india"] },
  { name:"UBS Jobs", url:"https://jobs.ubs.com/TGnewUI/Search/Home/Home?partnerid=25008&siteid=5012#home", note:"Banking & finance careers at UBS", tags:["new","enterprise"] },
  { name:"IBM Careers India", url:"https://www.ibm.com/in-en/careers/search?field_keyword_18[0]=Entry%20Level&field_keyword_18[1]=Internship&field_keyword_05[0]=India&sort=dcdate_desc", note:"IBM entry level & internships India", tags:["new","featured","enterprise","india"] },
  { name:"JobsForU.in", url:"https://jobsforu.in/", note:"Off-campus jobs & internships India", tags:["new","jobboard","india"] },
  { name:"Clarivate Careers", url:"https://careers.clarivate.com/home", note:"Analytics & IP company careers", tags:["new","enterprise"] },
  { name:"Forage", url:"https://www.theforage.com/jobs/6913b1e5181ddcda416788fd?oppType=job&countries=in", note:"Early career jobs & virtual internships", tags:["new","jobboard","india"] },
  { name:"Skill India Digital", url:"https://www.skillindiadigital.gov.in/opportunities", note:"Govt skill & job opportunities India", tags:["new","jobboard","india","nonprofit"] },
  { name:"HDPC Lateral Hiring", url:"https://hdpc.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/LateralHiring/jobs", note:"Oracle Cloud lateral hiring portal", tags:["new","enterprise"] },
  { name:"Synopsys Careers", url:"https://careers.synopsys.com/", note:"EDA & semiconductor tools company", tags:["new","enterprise"] },
  { name:"HPE Careers (Search)", url:"https://careers.hpe.com/us/en/search-results", note:"Hewlett Packard Enterprise jobs", tags:["new","enterprise"] },
  { name:"Quick Job Finder (linggame)", url:"https://linggame.xyz/", note:"Aggregated job finder tool", tags:["new","jobboard"] },
  { name:"Stripe India Jobs", url:"https://stripe.com/in/jobs", note:"Stripe jobs for India candidates", tags:["new","enterprise","saas","india"] },
  { name:"Chevron Careers", url:"https://careers.chevron.com/", note:"Energy company global careers", tags:["new","enterprise"] },
  { name:"HPE Careers", url:"https://careers.hpe.com/us/en", note:"Hewlett Packard Enterprise careers home", tags:["new","enterprise"] },
  { name:"Bain Technology", url:"https://www.bain.com/careers/work-with-us/our-work-areas/technology-engineering/", note:"Tech & engineering at Bain & Co", tags:["new","enterprise"] },
  { name:"GlobalLogic Careers", url:"https://www.globallogic.com/career-search-page/", note:"Product engineering services (Hitachi)", tags:["new","enterprise","india"] },
  { name:"Honeywell Jobs", url:"https://careers.honeywell.com/en/sites/Honeywell/jobs?sortBy=POSTING_DATES_DESC", note:"Industrial tech & automation", tags:["new","enterprise"] },
  { name:"Johnson Controls Jobs", url:"https://jobs.johnsoncontrols.com/job-search", note:"Engineering & IT jobs, India", tags:["new","enterprise","india"] },
  { name:"Nokia Careers", url:"https://jobs.nokia.com/en/sites/CX_1/jobs?lastSelectedFacet=TITLES&selectedTitlesFacet=SWA", note:"Telecom & software jobs", tags:["new","enterprise"] },
  { name:"American Express Careers", url:"https://aexp.eightfold.ai/careers", note:"Tech & finance jobs at Amex", tags:["new","enterprise"] },
  { name:"Zoho Careers", url:"https://careers.zohocorp.com/jobs/careers", note:"Indian SaaS giant jobs", tags:["new","featured","saas","india"] },
  { name:"Instahyre", url:"https://www.instahyre.com/candidate/opportunities/?matching=true", note:"Tech hiring platform India", tags:["new","jobboard","india","devtools"] },
  { name:"Nike Careers India", url:"https://careers.nike.com/jobs?location_name=India", note:"IT & software engineering at Nike India", tags:["new","enterprise","india"] },
  { name:"UnitedHealth Careers", url:"https://careers.unitedhealthgroup.com/job-search-results/?keyword=%22software%20engineering%22", note:"Healthcare tech, software engineering", tags:["new","enterprise"] },
  { name:"BP Careers India", url:"https://careers.bp.com/listing?production_bp_jobs%5BrefinementList%5D%5Blocation_list%5D%5B0%5D=India", note:"Energy company jobs India", tags:["new","enterprise","india"] },
  { name:"Quest Global", url:"https://careers.quest-global.com/global/en/search-results", note:"Engineering & tech services", tags:["new","enterprise","india"] },
  { name:"MyJobb.ai", url:"https://dashboard.myjobb.ai/dashboard", note:"AI job matching dashboard", tags:["new","jobboard","india"] },
  { name:"S&P Global Careers", url:"https://careers.spglobal.com/jobs", note:"Financial data & analytics careers", tags:["new","enterprise"] },
  { name:"Flexiple Jobs", url:"https://app.flexiple.com/talent/jobs", note:"Freelance & contract dev jobs", tags:["new","remote","devtools","jobboard"] },
  { name:"HackaJob", url:"https://user.hackajob.com/dashboard", note:"Tech job matching platform UK", tags:["new","devtools","jobboard"] },
  { name:"Students Circles", url:"https://studentscircles.com/", note:"Fresher jobs website India 2026", tags:["new","jobboard","india"] },
  { name:"Startup.jobs", url:"https://startup.jobs/", note:"Dev, design, marketing at startups", tags:["new","jobboard","startup"] },
  { name:"Startup.jobs Remote", url:"https://startup.jobs/remote-jobs?w=remote", note:"Remote startup jobs", tags:["new","remote","jobboard","startup"] },
  { name:"GoodSpace.ai", url:"https://goodspace.ai/member/dashboard", note:"AI-powered hiring platform India", tags:["new","jobboard","india"] },

  // ── Remote & General ──
  { name:"We Work Remotely", url:"https://weworkremotely.com/", note:"Top remote job board globally", tags:["new","featured","remote","jobboard"] },
  { name:"Job Board Search", url:"https://jobboardsearch.com/", note:"Meta-directory of 726+ job boards", tags:["new","jobboard"] },
  { name:"LHH Job Search", url:"https://www.lhh.com/en-us/search-jobs", note:"Career opportunities via LHH/Adecco", tags:["new","jobboard"] },
  { name:"Wellfound Jobs", url:"https://wellfound.com/jobs", note:"Startup job listings (AngelList)", tags:["new","startup","jobboard"] },
  { name:"PowerToFly", url:"https://powertofly.com/", note:"Diversity-focused tech jobs", tags:["new","remote","jobboard"] },
  { name:"SkipTheDrive", url:"https://www.skipthedrive.com/", note:"Work from home job listings", tags:["new","remote","jobboard"] },
  { name:"Authentic Jobs", url:"https://authenticjobs.com/", note:"Designer, dev & creative jobs", tags:["new","remote","devtools","jobboard"] },
  { name:"Jobspresso", url:"https://jobspresso.co/remote-work/", note:"1000+ remote tech job openings", tags:["new","remote","devtools","jobboard"] },
  { name:"RemoteFront", url:"https://www.remotefront.com/", note:"80,000+ remote roles updated hourly", tags:["new","featured","remote","jobboard"] },
  { name:"JustRemote", url:"https://justremote.co/", note:"Remote design, marketing, dev jobs", tags:["new","remote","jobboard"] },
  { name:"FlexJobs", url:"https://www.flexjobs.com/", note:"Vetted remote & flexible jobs", tags:["new","featured","remote","jobboard"] },
  { name:"WhoIsHiring", url:"https://whoishiring.io/", note:"Aggregated hiring listings", tags:["new","jobboard","devtools"] },
  { name:"RemoteOK", url:"https://remoteok.com/", note:"Remote jobs with open salaries", tags:["new","remote","devtools","jobboard"] },
  { name:"Dice", url:"https://www.dice.com/", note:"Tech job search engine US", tags:["new","devtools","jobboard"] },
  { name:"Remote.co", url:"https://remote.co/", note:"Remote jobs & company profiles", tags:["new","remote","jobboard"] },
  { name:"DevRemote", url:"https://devremote.io/", note:"1000+ curated remote dev jobs", tags:["new","remote","devtools","jobboard"] },
  { name:"Remotive", url:"https://remotive.com/", note:"Remote jobs in programming & more", tags:["new","featured","remote","devtools","jobboard"] },
  { name:"GitHub SWE Jobs 2025", url:"https://github.com/speedyapply/2025-SWE-College-Jobs", note:"Daily-updated SWE internship list", tags:["new","devtools","jobboard"] },

  // ── Indian IT Service Companies ──
  { name:"TCS Careers", url:"https://ibegin.tcs.com/iBegin/", note:"Tata Consultancy Services, India's largest IT firm", tags:["new","featured","enterprise","india","service"] },
  { name:"Infosys Careers", url:"https://career.infosys.com/joblist", note:"Infosys — global IT services & consulting", tags:["new","featured","enterprise","india","service"] },
  { name:"Wipro Careers", url:"https://careers.wipro.com/", note:"Wipro — IT, BPO & digital services", tags:["new","featured","enterprise","india","service"] },
  { name:"HCLTech Careers", url:"https://www.hcltech.com/careers", note:"HCL Technologies — IT services & products", tags:["new","featured","enterprise","india","service"] },
  { name:"Tech Mahindra Careers", url:"https://careers.techmahindra.com/", note:"Tech Mahindra — IT & telecom services", tags:["new","featured","enterprise","india","service"] },
  { name:"LTIMindtree Careers", url:"https://www.ltimindtree.com/careers/", note:"LTI + Mindtree merged IT services company", tags:["new","enterprise","india","service"] },
  { name:"Mphasis Careers", url:"https://www.mphasis.com/home/careers.html", note:"IT services, banking & finance focus", tags:["new","enterprise","india","service"] },
  { name:"Hexaware Careers", url:"https://hexaware.com/careers/", note:"IT & BPO services, automation focus", tags:["new","enterprise","india","service"] },
  { name:"Persistent Systems Careers", url:"https://www.persistent.com/careers/", note:"Product engineering & digital services", tags:["new","enterprise","india","service"] },
  { name:"Coforge Careers", url:"https://www.coforge.com/careers", note:"Formerly NIIT Technologies, IT services", tags:["new","enterprise","india","service"] },
  { name:"KPIT Technologies Careers", url:"https://www.kpit.com/careers/", note:"Automotive & mobility tech services", tags:["new","enterprise","india","service"] },
  { name:"Zensar Technologies Careers", url:"https://www.zensar.com/careers", note:"IT services & digital solutions", tags:["new","enterprise","india","service"] },
  { name:"Cyient Careers", url:"https://www.cyient.com/careers", note:"Engineering & technology services", tags:["new","enterprise","india","service"] },
  { name:"Birlasoft Careers", url:"https://www.birlasoft.com/careers", note:"IT services, CK Birla Group", tags:["new","enterprise","india","service"] },
  { name:"Mastech Digital Careers", url:"https://www.mastechdigital.com/careers/", note:"Digital transformation & staffing", tags:["new","enterprise","india","service"] },
  { name:"Sonata Software Careers", url:"https://www.sonata-software.com/careers", note:"Microsoft & cloud-focused IT services", tags:["new","enterprise","india","service"] },
  { name:"Sasken Careers", url:"https://www.sasken.com/careers", note:"Embedded & semiconductor services", tags:["new","enterprise","india","service"] },
  { name:"Firstsource Careers", url:"https://www.firstsource.com/careers/", note:"BPM & digital services", tags:["new","enterprise","india","service"] },
  { name:"Cognizant Careers", url:"https://careers.cognizant.com/global/en", note:"Global IT services & consulting", tags:["new","featured","enterprise","india","service"] },
  { name:"Accenture India Careers", url:"https://www.accenture.com/in-en/careers", note:"Global consulting & IT services India", tags:["new","featured","enterprise","india","service"] },
  { name:"ThoughtWorks Careers", url:"https://www.thoughtworks.com/careers", note:"Technology & consultancy firm", tags:["new","featured","enterprise","india","service"] },
  { name:"EPAM Systems Careers", url:"https://www.epam.com/careers", note:"Software engineering services", tags:["new","enterprise","india","service"] },
  { name:"Nagarro Careers", url:"https://www.nagarro.com/en/careers", note:"Digital product engineering services", tags:["new","enterprise","india","service"] },
  { name:"Nisum Careers", url:"https://www.nisum.com/careers", note:"Technology & consulting, India offices", tags:["new","enterprise","india","service"] },
  { name:"Tata Elxsi Careers", url:"https://www.tataelxsi.com/careers/", note:"Design & technology services", tags:["new","enterprise","india","service"] },
  { name:"3i Infotech Careers", url:"https://www.3i-infotech.com/careers/", note:"IT products & services", tags:["new","enterprise","india","service"] },
  { name:"Mphasis Freshers", url:"https://www.mphasis.com/home/careers/freshers.html", note:"Mphasis fresher hiring India", tags:["new","enterprise","india","service"] },

  // ── Indian MNCs & Global Tech India Offices ──
  { name:"Amazon India Jobs", url:"https://www.amazon.jobs/en/locations/india", note:"Amazon India — tech, ops, corporate", tags:["new","featured","enterprise","india","mnc"] },
  { name:"Microsoft India Careers", url:"https://careers.microsoft.com/v2/global/en/locations/india.html", note:"Microsoft India engineering & business roles", tags:["new","featured","enterprise","india","mnc"] },
  { name:"Meta Careers", url:"https://www.metacareers.com/", note:"Meta (Facebook) global careers incl. India", tags:["new","featured","enterprise","india","mnc"] },
  { name:"Apple Careers", url:"https://jobs.apple.com/en-us/search?location=india-IND", note:"Apple India engineering & design jobs", tags:["new","featured","enterprise","india","mnc"] },
  { name:"SAP India Careers", url:"https://jobs.sap.com/search/?q=&locationsearch=india", note:"SAP enterprise software, India labs", tags:["new","featured","enterprise","india","mnc"] },
  { name:"Oracle India Careers", url:"https://careers.oracle.com/jobs/#en/sites/jobsearch/jobs?location=India", note:"Oracle cloud & database, India", tags:["new","enterprise","india","mnc"] },
  { name:"Salesforce India Careers", url:"https://salesforce.wd12.myworkdayjobs.com/External_Career_Site?locationCountry=in", note:"Salesforce CRM & platform, India", tags:["new","enterprise","india","mnc","saas"] },
  { name:"Adobe India Careers", url:"https://careers.adobe.com/us/en/search-results?qcountry=India", note:"Adobe creative & document cloud India", tags:["new","featured","enterprise","india","mnc"] },
  { name:"Cisco India Careers", url:"https://jobs.cisco.com/jobs/SearchJobs/india", note:"Networking & cybersecurity giant, India", tags:["new","featured","enterprise","india","mnc"] },
  { name:"Intel India Careers", url:"https://jobs.intel.com/en/search#q=&t=Jobs&ac=30543", note:"Intel semiconductor, large India R&D centre", tags:["new","featured","enterprise","india","mnc"] },
  { name:"Qualcomm India Careers", url:"https://careers.qualcomm.com/careers/search?location=India", note:"Semiconductor & wireless tech India", tags:["new","enterprise","india","mnc"] },
  { name:"Texas Instruments India", url:"https://careers.ti.com/", note:"Semiconductor, major Bangalore campus", tags:["new","enterprise","india","mnc"] },
  { name:"Samsung R&D India", url:"https://www.samsungcareers.com/global/ind/", note:"Samsung India R&D — Bangalore & Noida", tags:["new","enterprise","india","mnc"] },
  { name:"PayPal India Careers", url:"https://careers.pypl.com/jobs/search?location_code=IND", note:"PayPal India tech & operations", tags:["new","enterprise","india","mnc"] },
  { name:"Mastercard India Careers", url:"https://careers.mastercard.com/us/en/search-results?qcountry=India", note:"Mastercard technology hub India", tags:["new","enterprise","india","mnc"] },
  { name:"Visa India Careers", url:"https://corporate.visa.com/en/jobs/search.html?q=&location=India", note:"Visa payments technology India", tags:["new","enterprise","india","mnc"] },
  { name:"Goldman Sachs India Careers", url:"https://higher.gs.com/roles?country=India", note:"Goldman Sachs Bengaluru/Hyderabad tech hub", tags:["new","enterprise","india","mnc"] },
  { name:"JPMorgan India Careers", url:"https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs?keyword=&lastSelectedFacet=LOCATIONS&selectedLocationsFacet=300000000272214", note:"JPMorgan Chase India technology hub", tags:["new","enterprise","india","mnc"] },
  { name:"Morgan Stanley India Careers", url:"https://www.morganstanley.com/people-opportunities/students-graduates/programs/technology", note:"Morgan Stanley India technology division", tags:["new","enterprise","india","mnc"] },
  { name:"Deutsche Bank India Careers", url:"https://careers.db.com/india/en/", note:"Deutsche Bank India tech & operations", tags:["new","enterprise","india","mnc"] },
  { name:"Barclays India Careers", url:"https://search.jobs.barclays/search-results?qcountry=India", note:"Barclays India Pune & Chennai centres", tags:["new","enterprise","india","mnc"] },
  { name:"HSBC India Careers", url:"https://www.hsbc.com/careers/jobs-and-internships/search-and-apply?jobsCountries=India", note:"HSBC India banking & technology roles", tags:["new","enterprise","india","mnc"] },
  { name:"Citi India Careers", url:"https://jobs.citi.com/search-jobs/India", note:"Citibank India technology & operations", tags:["new","enterprise","india","mnc"] },
  { name:"Wells Fargo India Careers", url:"https://www.wellsfargojobs.com/en/jobs/search/?q=&country=India", note:"Wells Fargo India Chennai & Hyderabad", tags:["new","enterprise","india","mnc"] },
  { name:"BNY Mellon India Careers", url:"https://bnymellon.eightfold.ai/careers?location=India", note:"BNY Mellon India Pune engineering hub", tags:["new","enterprise","india","mnc"] },
  { name:"BlackRock India Careers", url:"https://careers.blackrock.com/jobs/search?q=&location=India", note:"BlackRock India investment technology", tags:["new","enterprise","india","mnc"] },
  { name:"Fidelity India Careers", url:"https://jobs.fidelity.com/search-jobs/India", note:"Fidelity Investments India tech hub", tags:["new","enterprise","india","mnc"] },
  { name:"EY India Careers", url:"https://www.ey.com/en_in/careers", note:"Ernst & Young India consulting & tech", tags:["new","enterprise","india","mnc"] },
  { name:"Deloitte India Careers", url:"https://apply.deloitte.com/careers/SearchJobs/?885=%5B302173%5D&885_format=523&listFilterMode=1", note:"Deloitte India consulting & technology", tags:["new","enterprise","india","mnc"] },
  { name:"KPMG India Careers", url:"https://careers.kpmg.com/india/en", note:"KPMG India advisory & tech roles", tags:["new","enterprise","india","mnc"] },
  { name:"PwC India Careers", url:"https://www.pwc.in/careers.html", note:"PricewaterhouseCoopers India", tags:["new","enterprise","india","mnc"] },
  { name:"McKinsey India Careers", url:"https://www.mckinsey.com/careers/search-jobs#/?country=India", note:"McKinsey India consulting & analytics", tags:["new","enterprise","india","mnc"] },
  { name:"BCG India Careers", url:"https://careers.bcg.com/locations/asia-pacific/india", note:"Boston Consulting Group India", tags:["new","enterprise","india","mnc"] },
  { name:"Atlassian Careers", url:"https://www.atlassian.com/company/careers/all-jobs", note:"Jira & Confluence maker, remote-first", tags:["new","featured","enterprise","remote","saas","devtools"] },
  { name:"Uber Careers", url:"https://www.uber.com/us/en/careers/", note:"Uber global & India tech roles", tags:["new","enterprise","india","mnc"] },
  { name:"LinkedIn Careers", url:"https://careers.linkedin.com/", note:"LinkedIn (Microsoft) India & global", tags:["new","enterprise","india","mnc"] },
  { name:"Twitter / X Careers", url:"https://careers.x.com/en", note:"X (formerly Twitter) global careers", tags:["new","enterprise","mnc"] },
  { name:"Spotify Careers", url:"https://www.lifeatspotify.com/jobs", note:"Spotify global engineering roles", tags:["new","enterprise","mnc","remote"] },
  { name:"Booking.com Careers", url:"https://jobs.booking.com/careers", note:"Booking Holdings India & global", tags:["new","enterprise","mnc"] },
  { name:"Expedia Careers", url:"https://lifeatexpedia.com/", note:"Expedia Group India & global", tags:["new","enterprise","mnc","india"] },
  { name:"Workday Careers India", url:"https://workday.wd5.myworkdayjobs.com/Workday/jobs?q=india", note:"Workday India engineering & operations", tags:["new","enterprise","india","mnc","saas"] },
  { name:"ServiceNow Careers", url:"https://careers.servicenow.com/careers/jobs?location=India", note:"ServiceNow India — large Hyderabad hub", tags:["new","featured","enterprise","india","mnc","saas"] },
  { name:"VMware India Careers", url:"https://careers.vmware.com/main/jobs?stretchUnit=MILES&stretch=10&location=India", note:"VMware (Broadcom) India Bangalore hub", tags:["new","enterprise","india","mnc"] },
  { name:"Red Hat Careers", url:"https://www.redhat.com/en/jobs/search?location=India", note:"Red Hat India open-source & cloud", tags:["new","enterprise","india","mnc","devtools"] },
  { name:"Nutanix India Careers", url:"https://jobs.jobvite.com/nutanix/search?q=&l=India", note:"Nutanix cloud infrastructure India", tags:["new","enterprise","india","mnc"] },
  { name:"Zscaler Careers", url:"https://www.zscaler.com/careers/open-positions?location=india", note:"Cloud security, large India engineering", tags:["new","enterprise","india","mnc"] },
  { name:"Palo Alto Networks India", url:"https://jobs.paloaltonetworks.com/jobs/search?q=&location=India", note:"Cybersecurity leader India R&D", tags:["new","enterprise","india","mnc"] },
  { name:"Juniper Networks India", url:"https://jobs.juniper.net/jobs/search?q=&location=India", note:"Networking tech, Bangalore centre", tags:["new","enterprise","india","mnc"] },
  { name:"NetApp India Careers", url:"https://careers.netapp.com/jobs/search?q=&location=India", note:"Storage & cloud data services India", tags:["new","enterprise","india","mnc"] },
  { name:"Micron India Careers", url:"https://micron.eightfold.ai/careers?location=India", note:"Semiconductor / memory, India design centre", tags:["new","enterprise","india","mnc"] },
  { name:"Applied Materials India", url:"https://careers.appliedmaterials.com/careers/search?q=&location=India", note:"Semiconductor equipment, India R&D", tags:["new","enterprise","india","mnc"] },
  { name:"Siemens India Careers", url:"https://jobs.siemens.com/careers?query=&filters%5BcountryCode%5D%5B%5D=IN", note:"Siemens India engineering & tech", tags:["new","enterprise","india","mnc"] },
  { name:"Bosch India Careers", url:"https://www.bosch-career.in/", note:"Bosch India R&D — Bangalore software", tags:["new","enterprise","india","mnc"] },
  { name:"ABB India Careers", url:"https://careers.abb/global/en/india-jobs", note:"ABB India automation & electrification", tags:["new","enterprise","india","mnc"] },
  { name:"Schlumberger / SLB Careers", url:"https://careers.slb.com/", note:"Energy technology services, India hiring", tags:["new","enterprise","india","mnc"] },
  { name:"GE Careers India", url:"https://jobs.gecareers.com/global/en/search-results?qcountry=India", note:"GE India — aerospace, healthcare, energy", tags:["new","enterprise","india","mnc"] },
  { name:"Emerson India Careers", url:"https://hczw.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX/jobs?keyword=&lastSelectedFacet=LOCATION_COUNTRY&selectedLocationCountryFacet=India", note:"Emerson automation & industrial tech India", tags:["new","enterprise","india","mnc"] },
  { name:"Amadeus Careers India", url:"https://jobs.amadeus.com/en/search#q=&t=Jobs&ac=India", note:"Travel technology platform, India engineering", tags:["new","enterprise","india","mnc"] },
  { name:"Teradata India Careers", url:"https://careers.teradata.com/jobs/search?q=&location=India", note:"Data warehousing & analytics platform", tags:["new","enterprise","india","mnc"] },
  { name:"Twilio Careers", url:"https://www.twilio.com/en-us/company/jobs", note:"Cloud communications platform", tags:["new","enterprise","mnc","saas","devtools"] },
  { name:"Okta Careers", url:"https://www.okta.com/company/careers/", note:"Identity & access management SaaS", tags:["new","enterprise","mnc","saas"] },
  { name:"Splunk Careers", url:"https://www.splunk.com/en_us/careers.html", note:"Data platform, Cisco-owned India hub", tags:["new","enterprise","india","mnc","devtools"] },
  { name:"Snowflake Careers", url:"https://careers.snowflake.com/us/en", note:"Cloud data platform — India offices", tags:["new","featured","enterprise","india","mnc","saas"] },
  { name:"Databricks Careers", url:"https://www.databricks.com/company/careers/open-positions", note:"Data & AI platform, India engineering", tags:["new","featured","enterprise","india","mnc","saas"] },
  { name:"Confluent Careers", url:"https://www.confluent.io/careers/", note:"Kafka streaming platform, India offices", tags:["new","enterprise","india","mnc","devtools"] },
  { name:"MongoDB Careers", url:"https://www.mongodb.com/careers", note:"NoSQL database, India engineering hub", tags:["new","enterprise","india","mnc","devtools"] },
  { name:"Elastic Careers", url:"https://www.elastic.co/about/careers", note:"Elasticsearch & observability platform", tags:["new","enterprise","india","mnc","devtools"] },
  { name:"New Relic Careers", url:"https://newrelic.com/about/careers", note:"Observability platform, India offices", tags:["new","enterprise","india","mnc","devtools"] },
  { name:"Dynatrace Careers", url:"https://jobs.dynatrace.com/", note:"AI observability platform India", tags:["new","enterprise","india","mnc","saas"] },
  { name:"Freshworks Careers", url:"https://www.freshworks.com/company/careers/", note:"CRM & ITSM SaaS, founded in India", tags:["new","featured","enterprise","india","mnc","saas"] },
  { name:"Sprinklr Careers", url:"https://www.sprinklr.com/careers/", note:"Unified CXM platform India offices", tags:["new","enterprise","india","mnc","saas"] },
  { name:"BrowserStack Careers", url:"https://www.browserstack.com/careers", note:"Browser & app testing platform — India founded", tags:["new","featured","startup","india","devtools"] },
  { name:"Postman Careers", url:"https://www.postman.com/company/careers/", note:"API platform — founded in Bangalore", tags:["new","featured","startup","india","devtools"] },
  { name:"InMobi Careers", url:"https://www.inmobi.com/company/careers/", note:"Mobile advertising technology India", tags:["new","startup","india","mnc"] },
  { name:"CleverTap Careers", url:"https://clevertap.com/careers/", note:"Customer engagement & analytics India", tags:["new","startup","india","saas"] },
  { name:"MoEngage Careers", url:"https://www.moengage.com/about/careers/", note:"Customer engagement platform India", tags:["new","startup","india","saas"] },
  { name:"Chargebee Careers", url:"https://www.chargebee.com/careers/", note:"Subscription billing SaaS — India founded", tags:["new","startup","india","saas"] },
  { name:"Hasura Careers", url:"https://hasura.io/careers/", note:"GraphQL platform — Bangalore HQ", tags:["new","startup","india","devtools"] },
  { name:"Darwinbox Careers", url:"https://darwinbox.com/careers", note:"HR tech unicorn India", tags:["new","startup","india","saas"] },
  { name:"Leadsquared Careers", url:"https://www.leadsquared.com/careers/", note:"Marketing automation CRM India", tags:["new","startup","india","saas"] },
  { name:"WebEngage Careers", url:"https://webengage.com/careers/", note:"Customer data & engagement platform India", tags:["new","startup","india","saas"] },
  { name:"Icertis Careers", url:"https://www.icertis.com/company/careers/", note:"Contract intelligence SaaS unicorn India", tags:["new","startup","india","saas"] },

  // ── Indian Consumer Startups (Unicorns & Funded) ──
  { name:"Flipkart Careers", url:"https://www.flipkartcareers.com/#!/joblist", note:"India's largest e-commerce platform", tags:["new","featured","startup","india"] },
  { name:"Myntra Careers", url:"https://careers.myntra.com/", note:"Fashion e-commerce — Flipkart Group", tags:["new","startup","india"] },
  { name:"Meesho Careers", url:"https://meesho.io/careers", note:"Social commerce unicorn India", tags:["new","featured","startup","india"] },
  { name:"Nykaa Careers", url:"https://www.nykaa.com/careers/", note:"Beauty & fashion e-commerce India", tags:["new","startup","india"] },
  { name:"Swiggy Careers", url:"https://bytes.swiggy.com/swiggy-careers", note:"Food & quick delivery unicorn India", tags:["new","featured","startup","india"] },
  { name:"Zomato Careers", url:"https://www.zomato.com/careers", note:"Food delivery & Blinkit, listed company", tags:["new","featured","startup","india"] },
  { name:"Ola Cabs Careers", url:"https://ola.engineering/", note:"India's largest ride-hailing company", tags:["new","featured","startup","india"] },
  { name:"Rapido Careers", url:"https://rapido.bike/careers", note:"Bike taxi & delivery — fast growing India", tags:["new","startup","india"] },
  { name:"Urban Company Careers", url:"https://www.urbancompany.com/careers", note:"Home services unicorn India", tags:["new","startup","india"] },
  { name:"OYO Careers", url:"https://www.oyorooms.com/careers/", note:"Budget hospitality startup India", tags:["new","startup","india"] },
  { name:"MakeMyTrip Careers", url:"https://careers.makemytrip.com/", note:"Online travel agency India leader", tags:["new","startup","india"] },
  { name:"Ixigo Careers", url:"https://www.ixigo.com/careers", note:"Travel & train booking platform India", tags:["new","startup","india"] },
  { name:"Cars24 Careers", url:"https://www.cars24.com/careers/", note:"Used car marketplace unicorn India", tags:["new","startup","india"] },
  { name:"CarDekho Careers", url:"https://www.cardekho.com/careers", note:"Auto-tech platform India", tags:["new","startup","india"] },
  { name:"Spinny Careers", url:"https://www.spinny.com/careers", note:"Full-stack used car platform India", tags:["new","startup","india"] },
  { name:"Delhivery Careers", url:"https://www.delhivery.com/careers", note:"Logistics & supply chain unicorn India", tags:["new","startup","india"] },
  { name:"Shiprocket Careers", url:"https://www.shiprocket.in/careers/", note:"D2C logistics & shipping SaaS India", tags:["new","startup","india","saas"] },
  { name:"Razorpay Careers", url:"https://razorpay.com/jobs/", note:"Payments infrastructure unicorn India", tags:["new","featured","startup","india","saas"] },
  { name:"PhonePe Careers", url:"https://www.phonepe.com/careers/", note:"UPI payments & financial services India", tags:["new","featured","startup","india","saas"] },
  { name:"Paytm Careers", url:"https://careers.paytm.com/", note:"Payments & fintech listed company India", tags:["new","startup","india"] },
  { name:"CRED Careers", url:"https://careers.cred.club/", note:"Credit card rewards & fintech unicorn", tags:["new","featured","startup","india"] },
  { name:"BharatPe Careers", url:"https://www.bharatpe.com/careers", note:"Merchant payments & banking India", tags:["new","startup","india"] },
  { name:"Zepto Careers", url:"https://www.zeptonow.com/careers", note:"10-min grocery delivery unicorn India", tags:["new","featured","startup","india"] },
  { name:"Groww Careers", url:"https://groww.in/careers", note:"Investment & stock trading unicorn India", tags:["new","featured","startup","india"] },
  { name:"Zerodha Careers", url:"https://zerodha.com/careers/", note:"India's largest stockbroker by users", tags:["new","featured","startup","india"] },
  { name:"Upstox Careers", url:"https://upstox.com/careers/", note:"Discount broker & investing platform India", tags:["new","startup","india"] },
  { name:"Smallcase Careers", url:"https://smallcase.com/careers", note:"Thematic investment platform India", tags:["new","startup","india"] },
  { name:"Angel One Careers", url:"https://www.angelone.in/careers", note:"Stock broking & wealth management India", tags:["new","startup","india"] },
  { name:"KreditBee Careers", url:"https://www.kreditbee.in/careers", note:"Personal loan & credit platform India", tags:["new","startup","india"] },
  { name:"Slice Careers", url:"https://www.sliceit.com/careers", note:"Neobank & credit card startup India", tags:["new","startup","india"] },
  { name:"Jupiter Money Careers", url:"https://jupiter.money/careers", note:"Neobank & money management India", tags:["new","startup","india"] },
  { name:"Fi Money Careers", url:"https://fi.money/careers", note:"Smart banking app by Federal Bank India", tags:["new","startup","india"] },
  { name:"Niyo Careers", url:"https://www.niyo.co/careers", note:"Travel & salary accounts neobank India", tags:["new","startup","india"] },
  { name:"PolicyBazaar Careers", url:"https://careers.policybazaar.com/", note:"Insurance & financial products aggregator", tags:["new","startup","india"] },
  { name:"Acko Careers", url:"https://www.acko.com/careers/", note:"Digital-first insurance startup India", tags:["new","startup","india"] },
  { name:"Digit Insurance Careers", url:"https://www.godigit.com/about-digit/careers", note:"Listed insurtech company India", tags:["new","startup","india"] },
  { name:"Lendingkart Careers", url:"https://www.lendingkart.com/careers/", note:"SME lending fintech India", tags:["new","startup","india"] },
  { name:"BYJU'S Careers", url:"https://byjus.com/jobs/", note:"Edtech — note: undergoing restructuring", tags:["new","startup","india"] },
  { name:"Unacademy Careers", url:"https://unacademy.com/careers", note:"Online learning platform India", tags:["new","startup","india"] },
  { name:"Physics Wallah Careers", url:"https://www.pw.live/careers", note:"Edtech unicorn India — fast growing", tags:["new","featured","startup","india"] },
  { name:"upGrad Careers", url:"https://www.upgrad.com/careers/", note:"Online higher education platform India", tags:["new","startup","india"] },
  { name:"Vedantu Careers", url:"https://www.vedantu.com/careers", note:"Live online tutoring platform India", tags:["new","startup","india"] },
  { name:"Classplus Careers", url:"https://www.classplus.co/careers", note:"Edtech SaaS for educators India", tags:["new","startup","india","saas"] },
  { name:"Practo Careers", url:"https://www.practo.com/company/careers", note:"Healthcare platform & telemedicine India", tags:["new","startup","india"] },
  { name:"PharmEasy Careers", url:"https://pharmeasy.in/blog/careers/", note:"Online pharmacy & diagnostics India", tags:["new","startup","india"] },
  { name:"Healthkart Careers", url:"https://www.healthkart.com/jobs", note:"Health & nutrition e-commerce India", tags:["new","startup","india"] },
  { name:"Plum Careers", url:"https://www.plumhq.com/careers", note:"Group health insurance startup India", tags:["new","startup","india"] },
  { name:"Khatabook Careers", url:"https://khatabook.com/careers/", note:"Digital ledger & payments for SMBs India", tags:["new","startup","india","saas"] },
  { name:"OkCredit Careers", url:"https://okcredit.in/careers", note:"Digital khata book for merchants India", tags:["new","startup","india"] },
  { name:"Moglix Careers", url:"https://www.moglix.com/careers", note:"B2B industrial goods unicorn India", tags:["new","startup","india"] },
  { name:"Zetwerk Careers", url:"https://www.zetwerk.com/careers/", note:"Manufacturing marketplace unicorn India", tags:["new","startup","india"] },
  { name:"Porter Careers", url:"https://porter.in/careers", note:"Intra-city logistics platform India", tags:["new","startup","india"] },
  { name:"Dunzo Careers", url:"https://www.dunzo.com/careers", note:"Quick commerce India — check status", tags:["new","startup","india"] },
  { name:"InstaShop Careers", url:"https://www.instashop.com.eg/careers", note:"Quick grocery delivery, MENA/India", tags:["new","startup","india"] },
  { name:"Pepperfry Careers", url:"https://www.pepperfry.com/careers", note:"Online furniture marketplace India", tags:["new","startup","india"] },
  { name:"Lenskart Careers", url:"https://www.lenskart.com/careers", note:"Eyewear omnichannel unicorn India", tags:["new","featured","startup","india"] },
  { name:"Boat Lifestyle Careers", url:"https://www.boat-lifestyle.com/careers", note:"Consumer electronics brand India", tags:["new","startup","india"] },
  { name:"Noise Careers", url:"https://www.gonoise.com/pages/careers", note:"Smart wearables brand India", tags:["new","startup","india"] },
  { name:"boAt & Portronics", url:"https://portronics.com/pages/careers", note:"Consumer tech accessories brand India", tags:["new","startup","india"] },
  { name:"Ather Energy Careers", url:"https://www.atherenergy.com/careers", note:"Electric scooter manufacturer India", tags:["new","startup","india"] },
  { name:"Ola Electric Careers", url:"https://olaelectric.com/careers", note:"EV two-wheeler manufacturer India", tags:["new","featured","startup","india"] },
  { name:"Rivigo Careers", url:"https://www.rivigo.com/careers/", note:"Tech-enabled trucking startup India", tags:["new","startup","india"] },
  { name:"BlackBuck Careers", url:"https://www.blackbuck.com/careers/", note:"Trucking marketplace unicorn India", tags:["new","startup","india"] },
  { name:"Udaan Careers", url:"https://udaan.com/careers.html", note:"B2B e-commerce unicorn India", tags:["new","startup","india"] },
  { name:"Licious Careers", url:"https://www.licious.in/careers", note:"Direct-to-consumer meat & seafood India", tags:["new","startup","india"] },
  { name:"Country Delight Careers", url:"https://countrydelight.in/career", note:"Farm-to-home dairy & grocery India", tags:["new","startup","india"] },
  { name:"Ninjacart Careers", url:"https://ninjacart.in/careers.html", note:"Agri supply chain startup India", tags:["new","startup","india"] },
  { name:"Dehaat Careers", url:"https://www.dehaat.com/careers/", note:"Agri-tech platform India", tags:["new","startup","india"] },
  { name:"Sarvam AI Careers", url:"https://www.sarvam.ai/careers", note:"India-focused AI & language models startup", tags:["new","featured","startup","india","saas"] },
  { name:"Krutrim Careers", url:"https://krutrim.ai/careers", note:"Ola's AI startup, India LLM", tags:["new","startup","india"] },
  { name:"Agnikul Cosmos Careers", url:"https://www.agnikul.in/careers", note:"Space-tech rocket startup India", tags:["new","startup","india"] },
  { name:"Skyroot Aerospace Careers", url:"https://skyroot.in/careers", note:"Private space launch vehicle India", tags:["new","startup","india"] },
  { name:"Pixxel Careers", url:"https://www.pixxel.space/careers", note:"Earth observation satellite startup India", tags:["new","startup","india"] },
  { name:"TartanSense Careers", url:"https://www.tartansense.com/careers", note:"Agri-robotics startup India", tags:["new","startup","india"] },
  { name:"Sigmoid Careers", url:"https://www.sigmoid.com/careers/", note:"Data engineering consultancy India", tags:["new","startup","india","service"] },
  { name:"Mu Sigma Careers", url:"https://www.mu-sigma.com/careers", note:"Decision sciences & analytics India", tags:["new","startup","india","service"] },
  { name:"Fractal Analytics Careers", url:"https://fractal.ai/careers/", note:"AI & analytics company India/global", tags:["new","startup","india","service"] },
  { name:"LatentView Analytics Careers", url:"https://www.latentview.com/careers/", note:"Data analytics services India", tags:["new","startup","india","service"] },
  { name:"Tiger Analytics Careers", url:"https://www.tigeranalytics.com/careers/", note:"Data science consulting India", tags:["new","startup","india","service"] },
  { name:"Juspay Careers", url:"https://juspay.in/careers", note:"Payment orchestration platform India", tags:["new","startup","india","saas"] },
  { name:"Cashfree Payments Careers", url:"https://www.cashfree.com/careers/", note:"Payment gateway startup India", tags:["new","startup","india","saas"] },
  { name:"Open Financial Careers", url:"https://open.money/careers", note:"Neobank for businesses India", tags:["new","startup","india"] },
  { name:"Setu Careers", url:"https://setu.co/careers", note:"API infrastructure for fintech India", tags:["new","startup","india","devtools"] },

  // ── Additional Remote Job Boards ──
  { name:"Himalayas.app", url:"https://himalayas.app/jobs", note:"Remote job board with salary info", tags:["new","remote","jobboard"] },
  { name:"Arc.dev", url:"https://arc.dev/remote-jobs", note:"Remote developer job platform", tags:["new","remote","devtools","jobboard"] },
  { name:"Hired", url:"https://hired.com/", note:"Tech job marketplace — salary-first", tags:["new","remote","devtools","jobboard"] },
  { name:"Turing.com", url:"https://www.turing.com/jobs", note:"Remote software jobs for global devs", tags:["new","featured","remote","devtools","jobboard"] },
  { name:"Lemon.io", url:"https://lemon.io/", note:"Remote dev jobs for vetted engineers", tags:["new","remote","devtools","jobboard"] },
  { name:"Andela Careers", url:"https://andela.com/find-jobs/", note:"Remote tech jobs for Africa/India devs", tags:["new","remote","devtools","jobboard"] },
  { name:"Contra Freelance", url:"https://contra.com/features/find-freelance-jobs", note:"Commission-free freelance platform", tags:["new","remote","devtools","jobboard"] },
  { name:"Jobgether", url:"https://jobgether.com/", note:"Remote & hybrid job matching platform", tags:["new","remote","jobboard"] },
  { name:"Remote Leaf", url:"https://remoteleaf.com/", note:"Curated remote jobs newsletter & board", tags:["new","remote","jobboard"] },
  { name:"EuropeRemotely", url:"https://europeremotely.com/", note:"Remote jobs hiring across Europe/global", tags:["new","remote","jobboard"] },
  { name:"Dynamite Jobs", url:"https://dynamitejobs.com/", note:"Remote startup jobs board", tags:["new","remote","startup","jobboard"] },
  { name:"Outsourcely", url:"https://www.outsourcely.com/remote-workers", note:"Remote worker hiring platform", tags:["new","remote","jobboard"] },
  { name:"Remote.io", url:"https://remote.io/", note:"Remote job aggregator", tags:["new","remote","jobboard"] },
  { name:"Joblist Remote", url:"https://joblist.app/", note:"Job search aggregator with remote filter", tags:["new","remote","jobboard"] },
  { name:"Flexa Careers", url:"https://flexa.careers/", note:"Genuinely flexible company job board", tags:["new","remote","jobboard"] },
  { name:"4 Day Week Jobs", url:"https://4dayweek.io/", note:"4-day work week job listings", tags:["new","remote","jobboard"] },
  { name:"Remote First Jobs", url:"https://remotefirstjobs.com/", note:"Companies that are remote-first", tags:["new","remote","jobboard"] },
];

let activeFilter = 'all';

function setFilter(f, btn) {
  activeFilter = f;
  document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
  filterCards();
}

function filterCards() {
  const q = document.getElementById('search').value.toLowerCase().trim();
  const grid = document.getElementById('grid');
  const cards = grid.querySelectorAll('a.card');
  let visible = 0;
  cards.forEach(card => {
    const name = card.dataset.name.toLowerCase();
    const note = card.dataset.note.toLowerCase();
    const tags = card.dataset.tags;
    const matchFilter = activeFilter === 'all' || tags.includes(activeFilter);
    const matchSearch = !q || name.includes(q) || note.includes(q);
    if (matchFilter && matchSearch) { card.style.display = ''; visible++; }
    else card.style.display = 'none';
  });
  document.getElementById('visible-count').textContent = visible + ' shown';
  document.getElementById('no-results').style.display = visible === 0 ? 'block' : 'none';
}

function buildGrid() {
  const grid = document.getElementById('grid');
  const noResults = document.getElementById('no-results');
  companies.forEach(c => {
    const a = document.createElement('a');
    a.href = c.url;
    a.target = '_blank';
    a.rel = 'noopener noreferrer';
    a.className = 'card';
    a.dataset.name = c.name.toLowerCase();
    a.dataset.note = c.note.toLowerCase();
    a.dataset.tags = c.tags.join(',');

    const tagHtml = c.tags.map(t => `<span class="tag ${t === 'new' ? 'new' : t === 'featured' ? 'featured' : ''}">${t}</span>`).join('');
    const shortUrl = c.url.replace('https://','').replace(/\/$/,'');

    a.innerHTML = `
      <div class="card-top">
        <span class="card-name">${c.name}</span>
        <svg class="card-arrow" viewBox="0 0 24 24"><line x1="7" y1="17" x2="17" y2="7"/><polyline points="7 7 17 7 17 17"/></svg>
      </div>
      <span class="card-url">${shortUrl}</span>
      <div class="card-tags">${tagHtml}</div>
      <p class="card-note">${c.note}</p>
    `;
    grid.insertBefore(a, noResults);
  });
  document.getElementById('total-count').textContent = companies.length;
  document.getElementById('visible-count').textContent = companies.length + ' shown';
}

buildGrid();